on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x]
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install Install System dependencies
      if: matrix.platform == 'ubuntu-latest'
      run: sudo apt update && sudo apt install -y --no-install-recommends libasound2-dev
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: go test ./...
